app = "telegram-checkin-bot-v3"

primary_region = "sin"

[env]
  TELEGRAM_TOKEN = "7620072160:AAEbty9W7vqZ5sgNAY8I0ACWYCIiNVrNZDs"
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
