app = "telegram-checkin-bot-v3"

[env]
  TELEGRAM_TOKEN = "7620072160:AAEbty9W7vqZ5sgNAY8I0ACWYCIiNVrNZDs"

[build]
  dockerfile = "Dockerfile"


[build]
  image = "python:3.10"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
